version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./react-twitter
      dockerfile: Dockerfile
    volumes:
      - ./react-twitter:/app
      - /app/node_modules  # Prevent host overwrite of container's node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
