[tool.ruff]
exclude = ["scripts/", "manage.py", "asgi.py", "wsgi.py", "*/migrations/"]
line-length = 120

indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D104",
    "D100",
    "D103",
    "D211",
    "D213",
    "D101",
    "D102",
    "D105",
    "D106",
    "D107",
    "D203",
    "ISC001",
    "COM812",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",    # asserts allowed in tests...
    "ARG",     # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",     # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "RUF001",  # Ruff had a problem with "’" in text: The two password fields didn’t match.
    "PLR2004", # Ruff is pushing for constants instead of ints.
]
